CODE/WebApp/WebApp/Areas/RBAC/Controllers/AuthManageController.cs
using MyFrame.Infrastructure.OptResult;
using MyFrame.RBAC.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Controllers;
using MyFrame.Infrastructure.Extension;
using MyFrame.RBAC.Model;
using WebApp.Extensions.ActionResult;
using WebApp.Extensions.Filters;
using MyFrame.RBAC.Service.Interface;

namespace WebApp.Areas.RBAC.Controllers
{
    /// <summary>
    /// 角色权限分配控制器
    /// </summary>
    public class AuthManageController : BaseController
    {
        IRolePermissionService _rolePermissionSrv;
        public AuthManageController(IRolePermissionService rolePermissionSrv, IOperationService optSrv)
            : base(optSrv)
        {
            _rolePermissionSrv = rolePermissionSrv;
        }

        [LoginCheck]
        public ActionResult Index()
        {
            base.SetOptPermissions();
            return View();
        }

        [HttpPost]
        [AuthCheck]
        public JsonResult SavePermission(int roleId, int[] perIds, int perType, int? moduleId = null)
        {
            var permissionType = perType.ConvertTo<PermissionType>();
            if (permissionType == PermissionType.Module)
            {
                //模块权限
                OperationResult rst = _rolePermissionSrv.AssignModulePermissions(roleId, perIds);
                if (rst.ResultType != OperationResultType.Success)
                {
                    return Json(new { code = rst.ResultType, message = rst.Message });
                }
                return Json(new { code = OperationResultType.Success, message = "模块权限分配成功" });
            }
            else if (permissionType == PermissionType.Operation)
            {
                if (moduleId == null)
                {
                    return Json(new { code = OperationResultType.ParamError, message = "模块id不能为空" });
                }
                OperationResult rst = _rolePermissionSrv.AssignOptPermissions(roleId, (int)moduleId, perIds);
                if (rst.ResultType != OperationResultType.Success)
                {
                    return Json(new { code = rst.ResultType, message = rst.Message });
                }
                return Json(new { code = OperationResultType.Success, message = "操作权限分配成功" });
            }
            return Json(new { code = OperationResultType.ParamError, message = "未识别的权限类型" });
        }

        [HttpPost]
        [AuthCheck]
        public JsonResult SaveAllPermission(int roleId, int perType)
        {
            OperationResult rst = new OperationResult();
            var permissionType = perType.ConvertTo<PermissionType>();
            if (permissionType == PermissionType.Module)
            {
                rst = _rolePermissionSrv.AssignAllModulePermissions(roleId);
                if (rst.ResultType != OperationResultType.Success)
                {
                    return Json(new { code = rst.ResultType, message = rst.Message });
                }
            }
            else if (permissionType == PermissionType.Operation)
            {
                rst = _rolePermissionSrv.AssignAllOptPermissions(roleId);
                if (rst.ResultType != OperationResultType.Success)
                {
                    return Json(new { code = rst.ResultType, message = rst.Message });
                }
            }
            else
            {
                return Json(new { code = OperationResultType.ParamError, message = "未识别的权限类型" });
            }
            return Json(new { code = OperationResultType.Success, message = "权限分配成功" });
        }

        public JsonResult GetPermission(int roleId)
        {
            OperationResult rst = _rolePermissionSrv.Find(r => r.RoleId == roleId);
            if (rst.ResultType != OperationResultType.Success)
            {
                return Json(new { code = rst.ResultType, message = rst.Message }, JsonRequestBehavior.AllowGet);
            }
            return new JsonNetResult
                {
                    Data = new { code = rst.ResultType, message = "角色权限获取成功", rows = rst.AppendData },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
        }
    }
}

CODE/WebApp/WebApp/Areas/RBAC/Controllers/RoleController.cs
using MyFrame.RBAC.Service;
using MyFrame.RBAC.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using WebApp.Controllers;
using WebApp.Extensions.Filters;
using MyFrame.Infrastructure.Extension;
using MyFrame.Infrastructure.Pagination;
using MyFrame.Infrastructure.OptResult;
using WebApp.Extensions.ActionResult;
using MyFrame.RBAC.ViewModel;
using WebApp.Extensions.Session;

using MyFrame.RBAC.Service.Interface;
using MyFrame.Infrastructure.Common;

namespace WebApp.Areas.RBAC.Controllers
{
    public class RoleController : BaseController
    {
        private readonly IRoleService _roleSrv;
        public RoleController(IRoleService roleSrv, IOperationService optSrv)
            : base(optSrv)
        {
            _roleSrv = roleSrv;
        }

        /// <summary>
        /// 列表界面
        /// </summary>
        /// <returns></returns>
        [LoginCheck]
        public ActionResult Index()
        {
            base.SetOptPermissions();
            return View();
        }

        public JsonResult GetRoleFullInfoByPage(int pageNumber, int pageSize)
        {
            Expression<Func<Role, bool>> where = r => true;
            var roleName = HttpContext.Request["RoleName"];
            if (!string.IsNullOrEmpty(roleName))
            {
                where = where.And(r => r.RoleName.Contains(roleName));
            }
            var pageArgs = new PageArgs { PageSize = pageSize, PageIndex = pageNumber };
            var result = _roleSrv.FindByPageWithFullInfo(where, query => query.OrderBy(r => r.SortOrder), pageArgs);

            if (result.ResultType == OperationResultType.Success)
            {
                return new JsonNetResult
                {
                    Data = new { code = result.ResultType, message = "数据获取成功", total = pageArgs.RecordsCount, rows = result.AppendData },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    DateTimeFormat = "yyyy-MM-dd HH:mm:ss"
                };
            }
            else
            {
                return Json(new { code = result.ResultType, message = result.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetRolesSimpleInfoByPage(int pageNumber, int pageSize)
        {
            Expression<Func<Role, bool>> where = r => true;//
            var roleName = HttpContext.Request["RoleName"];
            if (!string.IsNullOrEmpty(roleName))
            {
                where = where.And(r => r.RoleName.Contains(roleName));
            }
            var pageArgs = new PageArgs { PageSize = pageSize, PageIndex = pageNumber };
            var result = _roleSrv.FindBySelectorByPage(where,
                r => new
                {
                    Id = r.Id,
                    RoleName = r.RoleName,
                    Remark = r.Remark
                },
                query => query.OrderBy(r => r.SortOrder),
                pageArgs);

            if (result.ResultType == OperationResultType.Success)
            {
                return new JsonNetResult
                {
                    Data = new { code = result.ResultType, message = "数据获取成功", total = pageArgs.RecordsCount, rows = result.AppendData },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    DateTimeFormat = "yyyy-MM-dd HH:mm:ss"
                };
            }
            else
            {
                return Json(new { code = result.ResultType, message = result.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult GetRolesBySelector()
        {
            Expression<Func<Role, bool>> where = r => true;//
            var result = _roleSrv.FindBySelectorByPage(where, r => new
            {
                Id = r.Id,
                RoleName = r.RoleName,
                SortOrder = r.SortOrder,
                Remark = r.Remark
            }, query => query.OrderBy(r => r.SortOrder), new PageArgs { PageSize = 10, PageIndex = 1 });
            return new JsonNetResult
            {
                Data = new { code = result.ResultType, message = "数据获取成功", total = 1000, rows = result.AppendData },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                DateTimeFormat = "yyyy-MM-dd HH:mm:ss"
            };
        }

        public ActionResult Add()
        {
            RoleViewModel roleVM = new RoleViewModel();
            return PartialView(roleVM);
        }

        /// <summary>
        /// 列表帮助
        /// </summary>
        /// <returns></returns>
        public ActionResult GridHelp()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthCheck]
        public JsonResult Add(RoleViewModel roleVM)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { code = OperationResultType.ParamError, message = base.ParseModelStateErrorMessage(ModelState) });
            }

            var role = OOMapper.Map<RoleViewModel,Role>(roleVM);
            role.Creator = HttpContext.Session.GetUserId();
            role.CreateTime = DateTime.Now;

            OperationResult result = _roleSrv.Add(role);

            if (result.ResultType != OperationResultType.Success)
            {
                return Json(new { code = result.ResultType, message = result.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "添加成功" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthCheck]
        public JsonResult Edit(RoleViewModel roleVM)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { code = OperationResultType.ParamError, messgae = base.ParseModelStateErrorMessage(ModelState) });
            }

            var role = OOMapper.Map<RoleViewModel,Role>(roleVM);
            role.LastModifier = HttpContext.Session.GetUserId();
            role.LastModifyTime = DateTime.Now;

            var rst = _roleSrv.UpdateDetail(role);

            if (rst.ResultType != OperationResultType.Success)
            {
                return Json(new { code = rst.ResultType, message = rst.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "修改成功" });
        }

        [HttpPost]
        [AuthCheck]
        public JsonResult Delete()
        {
            int[] roleIds = null;
            using (var reader = new System.IO.StreamReader(HttpContext.Request.InputStream))
            {
                string data = reader.ReadToEnd();
                try
                {
                    roleIds = data.DeSerializeFromJson<int[]>();
                }
                catch (Exception ex)
                {
                    return Json(new { code = OperationResultType.ParamError, message = ex.GetDeepestException().Message });
                }
            }
            if (roleIds == null || roleIds.Length < 1)
            {
                return Json(new { code = OperationResultType.ParamError, message = "角色id列表不能为空" });
            }
            OperationResult result = _roleSrv.DeleteWithRelations(roleIds);
            if (result.ResultType != OperationResultType.Success)
            {
                return Json(new { code = result.ResultType, message = result.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "删除成功" });
        }
    }
}

CODE/WebApp/WebApp/Areas/RBAC/Views/AuthManage/Index.cshtml
@using WebApp.Extensions.Html
@using MyFrame.RBAC.Model
@{
    var opts = ViewData["Opts"] as List<Operation>;
}
<style type="text/css">
    .div-col {
        padding: 2px;
    }
</style>
<div class="row" style="margin-top:10px;">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">权限分配</h3>
            </div>
            <div class="box-body">
                <div class="row" style="min-height:480px;">
                    <div class="col-xs-3">
                        <div class="form-inline">
                            <div class="form-group">
                                <input type="text" id="txtSearchRoleName_AuthManage" name="RoleName" class="form-control" placeholder="角色名" />
                                <button id="btnSearchRoles_AuthManage" type="button" class="btn btn-success">
                                    <span class="glyphicon glyphicon-search">查询</span>
                                </button>
                            </div>
                        </div>
                        <table id="gridRoles_AuthManage" class="table table-bordered table-striped table-hover" cellspacing="0"></table>
                    </div>
                    <div class="col-xs-8">
                        <div id="toolbar" class="row" style="margin:4px 0px;padding:0px;">
                            <div class="btn-group">
                                @{
                                    if (opts != null && opts.Count > 0)
                                    {
                                        foreach (var opt in opts)
                                        {
                                            @Html.OptButton(opt);
                                        }
                                    }
                                }
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-5 div-col">
                                <div id="treeModule_AuthManage"></div>
                            </div>
                            <div class="col-sm-7 div-col">
                                <table id="gridOpts_AuthManage" class="table table-bordered table-striped table-hover" cellspacing="0"></table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/libs/rbac/authmanage/index.js"></script>
<script>
    $(function () {
        authmanage.init({
            urlSearchRoles: "@Html.Raw(Url.Action("GetRolesSimpleInfoByPage","Role", new { pageNumber = 1, pageSize = 20 }))",
            urlSearchModules: "@Html.Raw(Url.Action("GetModulesSimpleInfoByPage", "Module", new { pageNumber = 1, pageSize = 1000 }))",
            urlSearchOpts: "@Html.Raw(Url.Action("GetOptsSimpleInfoByPage", "Operation", new { pageNumber = 1, pageSize = 1000 }))",
            urlGetPermission: "@Url.Action("GetPermission", "AuthManage")",
        });
    });
</script>