CODE/WebApp/WebApp/Areas/RBAC/Controllers/ModuleController.cs
using MyFrame.Infrastructure.Extension;
using MyFrame.Infrastructure.OptResult;
using MyFrame.RBAC.Service;
using MyFrame.RBAC.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using WebApp.Extensions.ActionResult;
using WebApp.Extensions.Filters;
using MyFrame.Infrastructure.Pagination;
using MyFrame.RBAC.ViewModel;
using WebApp.Controllers;
using WebApp.Extensions.Session;

using MyFrame.RBAC.Service.Interface;
using WebApp.Areas.RBAC.ViewModel;
using MyFrame.Infrastructure.Common;


namespace WebApp.Areas.RBAC.Controllers
{
    public class ModuleController : BaseController
    {
        IModuleService _moduleSrv;

        public ModuleController(IModuleService moduleSrv, IOperationService optSrv)
            : base(optSrv)
        {
            _moduleSrv = moduleSrv;
        }

        [LoginCheck]
        public ActionResult Index()
        {
            base.SetOptPermissions();
            return View();
        }

        public JsonResult GetModulesFullInfoByPage(int pageNumber, int pageSize)
        {
            Expression<Func<Module, bool>> where = m => true;
            var code = HttpContext.Request["Code"];
            if (!string.IsNullOrEmpty(code))
            {
                where = where.And(m => m.Code.Contains(code));
            }
            var name = HttpContext.Request["Name"];
            if (!string.IsNullOrEmpty(name))
            {
                where = where.And(m => m.Name.Contains(name));
            }
            var pageArgs = new PageArgs { PageSize = pageSize, PageIndex = pageNumber };

            var result = _moduleSrv.FindByPageWithFullInfo(where,
                query => query.OrderBy(m => m.ParentId).ThenBy(m => m.SortOrder),
                pageArgs);

            if (result.ResultType == OperationResultType.Success)
            {
                return new JsonNetResult
                {
                    Data = new { code = result.ResultType, message = "数据获取成功", total = pageArgs.RecordsCount, rows = result.AppendData },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    DateTimeFormat = "yyyy-MM-dd HH:mm:ss"
                };
            }
            else
            {
                return Json(new { code = result.ResultType, message = result.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetModulesSimpleInfoByPage(int pageNumber, int pageSize)
        {
            Expression<Func<Module, bool>> where = r => true;//
            var moduleName = HttpContext.Request["ModuleName"];
            if (!string.IsNullOrEmpty(moduleName))
            {
                where = where.And(m => m.Name.Contains(moduleName));
            }
            var pageArgs = new PageArgs { PageSize = pageSize, PageIndex = pageNumber };
            var result = _moduleSrv.FindByPageWithSimpleInfo(where, query => query.OrderBy(r => r.SortOrder), pageArgs);

            if (result.ResultType == OperationResultType.Success)
            {
                var modules = BuildModulesTree(result.AppendData as List<ModuleSimpleViewModel>);
                var formatObj = FormatDataForTreeView(modules);
                return new JsonNetResult
                {
                    Data = new { code = result.ResultType, message = "数据获取成功", total = pageArgs.RecordsCount, rows = formatObj },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    DateTimeFormat = "yyyy-MM-dd HH:mm:ss"
                };
            }
            else
            {
                return Json(new { code = result.ResultType, message = result.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// 树帮助
        /// </summary>
        /// <returns></returns>
        public ActionResult TreeHelp()
        {
            return PartialView();
        }

        public ActionResult Add()
        {
            var vmModule = new ModuleViewModel();
            return View(vmModule);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthCheck]
        public JsonResult Add(ModuleViewModel vmModule)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { code = OperationResultType.ParamError, message = base.ParseModelStateErrorMessage(ModelState) });
            }
            var module = OOMapper.Map<ModuleViewModel, Module>(vmModule);
            module.Creator = HttpContext.Session.GetUserId();
            module.CreateTime = DateTime.Now;

            OperationResult result = _moduleSrv.Add(module);

            if (result.ResultType != OperationResultType.Success)
            {
                return Json(new { code = result.ResultType, message = result.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "添加成功" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthCheck]
        public JsonResult Edit(ModuleViewModel vmModule)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { code = OperationResultType.ParamError, message = base.ParseModelStateErrorMessage(ModelState) });
            }
            var module = OOMapper.Map<ModuleViewModel, Module>(vmModule);
            module.LastModifier = HttpContext.Session.GetUserId();
            module.LastModifyTime = DateTime.Now;

            OperationResult result = _moduleSrv.UpdateDetail(module);

            if (result.ResultType != OperationResultType.Success)
            {
                return Json(new { code = result.ResultType, message = result.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "修改成功" });
        }

        [HttpPost]
        [AuthCheck]
        public JsonResult Delete()
        {
            int[] moduleIds = null;
            using (var reader = new System.IO.StreamReader(HttpContext.Request.InputStream))
            {
                string data = reader.ReadToEnd();
                try
                {
                    moduleIds = data.DeSerializeFromJson<int[]>();
                }
                catch (Exception ex)
                {
                    return Json(new { code = OperationResultType.ParamError, message = ex.GetDeepestException().Message });
                }
            }
            if (moduleIds == null || moduleIds.Length < 1)
            {
                return Json(new { code = OperationResultType.ParamError, message = "模块id列表不能为空" });
            }
            OperationResult result = _moduleSrv.Delete(m => moduleIds.Contains(m.Id));
            if (result.ResultType != OperationResultType.Success)
            {
                return Json(new { code = result.ResultType, message = result.Message });
            }
            return Json(new { code = OperationResultType.Success, message = "删除成功" });
        }

        public static List<ModuleSimpleViewModel> BuildModulesTree(List<ModuleSimpleViewModel> modules)
        {
            List<ModuleSimpleViewModel> listVM = new List<ModuleSimpleViewModel>();
            if (modules == null || modules.Count < 1)
            {
                return listVM;
            }
            //递归构建菜单树
            var firstList = modules.Where(m => m.ParentId == null).OrderBy(m => m.SortOrder);
            foreach (var vm in firstList)
            {
                SetSubModules(vm, modules);
            }
            //只添加第一层即可
            listVM.AddRange(firstList);

            return listVM;
        }

        public List<ModuleTreeNode> FormatDataForTreeView(IEnumerable<ModuleSimpleViewModel> modules)
        {
            if (modules == null || modules.Count() < 1)
            {
                return new List<ModuleTreeNode>();
            }
            List<ModuleTreeNode> treeNodes = new List<ModuleTreeNode>();
            foreach (var module in modules)
            {
                var node = new ModuleTreeNode { id = module.Id.ToString(), text = module.Name, sort = module.SortOrder };
                if (module.SubModules != null && module.SubModules.Count() > 0)
                {
                    node.nodes = new List<ModuleTreeNode>();
                    node.nodes.AddRange(FormatDataForTreeView(module.SubModules));
                }
                treeNodes.Add(node);
            }
            return treeNodes;
        }

        private static void SetSubModules(ModuleSimpleViewModel parent, List<ModuleSimpleViewModel> srcList)
        {
            if (parent == null || srcList == null || srcList.Count < 1)
            {
                return;
            }
            var subList = srcList.Where(m => m.ParentId == parent.Id).OrderBy(m => m.SortOrder);
            //设置parent
            parent.SubModules = subList.ToList();
            //递归处理subList
            foreach (var vm in parent.SubModules)
            {
                SetSubModules(vm, srcList);
            }
        }
    }
}

CODE/WebApp/WebApp/Areas/RBAC/Views/Module/Add.cshtml
@using MyFrame.RBAC.ViewModel
@model ModuleViewModel
<link href="~/libs/plugins/iCheck/square/blue.css" rel="stylesheet" />
<div id="form-add-module">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.Code, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Code)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.Name, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.LinkUrl, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.LinkUrl, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LinkUrl)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.Icon, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Icon, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Icon)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.SortOrder, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.SortOrder, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SortOrder)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.ParentName, new { @class = "control-label pull-right" })
        </div>
        <div class="col-sm-8">
            @Html.HiddenFor(m => m.ParentId)
            <div class="input-group">
                @Html.TextBoxFor(m => m.ParentName, new { @class = "form-control", @readonly = "readonly" })
                <div id="btnHelpParentModule" class="btn btn-primary input-group-addon">选择...</div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.Enabled, new { @class = "control-label pull-right" })
        </div>
        <div class="checkbox icheck col-sm-8">
            @Html.CheckBoxFor(m => m.Enabled, new { @class = "myCheck" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3">
            @Html.LabelFor(m => m.IsSystem, new { @class = "control-label pull-right" })
        </div>
        <div class="checkbox icheck col-sm-8">
            @Html.CheckBoxFor(m => m.IsSystem, new { @class = "myCheck" })
        </div>
    </div>
</div>
<script>
    var moduleAdd = {
        urlModuleTreeHelp: "@Url.Action("TreeHelp")",
        btnHelpParentModule: $('#btnHelpParentModule'),
        init: function () {
            moduleAdd.btnHelpParentModule.click(function () {
                //console.log('modulemanage.btnHelpParentModule.click enter');
                modalFormHelp.show({
                    title: '模块帮助',
                    urlHelp: moduleAdd.urlModuleTreeHelp,
                    urlParams: {},
                    onSubmitCallback: function () {
                        //1、获取选择的节点
                        var moduleData = moduleTreeHelp.treeModule.getSelectedData(['id', 'text']);
                        //console.log(moduleData);
                        if (gFunc.isNull(moduleData) || moduleData.length < 1) {
                            return false;
                        }
                        //2、给界面赋值
                        $('#ParentId').val(moduleData[0]['id']);
                        $('#ParentName').val(moduleData[0]['text']);
                        console.log('#ParentName:' + $('#ParentName').val());
                        return true;
                    },
                    onLoadCallback: function () {
                        console.log('onLoadCallback called');

                    }
                });
            });
        }
    };

    $(function () {
        gFunc.setCheckBoxStyle('input.myCheck');
        moduleAdd.init();
    });
</script>

CODE/WebApp/WebApp/Areas/RBAC/Views/Module/Index.cshtml
@using WebApp.Extensions.Html
@using MyFrame.RBAC.Model
@{
    var opts = ViewData["Opts"] as List<Operation>;
}
<div class="row" style="margin-top:10px;">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">模块管理</h3>
            </div>
            <div class="box-body">
                <div id="toolbar" class="container" style="margin:4px 0px;">
                    <div class="row">
                        <div class="col-sm-3 btn-group">
                            @{
                                if (opts != null && opts.Count > 0)
                                {
                                    foreach (var opt in opts)
                                    {
                                        @Html.OptButton(opt);
                                    }
                                }
                            }
                        </div>
                        <div class="col-sm-2" style="padding:0px;">
                            <input type="text" id="txtSearchCode_ModuleManage" name="Code" class="form-control" placeholder="模块编号" />
                        </div>
                        <div class="col-sm-2" style="padding:0px;">
                            <input type="text" id="txtSearchName_ModuleManage" name="Name" class="form-control" placeholder="模块名称" />
                        </div>
                        <div class="col-sm-1" style="padding-left:2px;">
                            <button id="btnSearch_ModuleManage" type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-search">查询</span>
                            </button>
                        </div>
                    </div>
                </div>
                <table id="grid_ModuleManage" class="table table-bordered table-striped table-hover" cellspacing="0"></table>
            </div>
        </div>
    </div>
</div>
<script src="~/libs/rbac/module/index.js"></script>
<script type="text/javascript">
    $(function () {
        modulemanage.init({
            urlAdd: "@Url.Action("Add")",
            urlSearch: "@Url.Action("GetModulesFullInfoByPage")",
            urlModuleTreeHelp: "@Url.Action("TreeHelp")"
        });
    });
</script>

CODE/WebApp/WebApp/Areas/RBAC/Views/Module/TreeHelp.cshtml
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                <div id="toolbar" class="container">
                    <div class="row">
                        <div class="col-sm-2" style="padding:0px;">
                            <input type="text" id="txtModuleName_Help" name="ModuleName" class="form-control" placeholder="模块名" />
                        </div>
                        <div class="col-sm-1" style="padding-left:2px;">
                            <button id="btnModuleSearch_Help" type="button" class="btn btn-success">
                                <span class="glyphicon glyphicon-search">查询</span>
                            </button>
                        </div>
                    </div>
                </div>
                <div id="treeModule_Help"></div>
            </div>
        </div>
    </div>
</div>
<script src="~/libs/plugins/bootstrap-treeview/bootstrap-treeview.js"></script>
<script src="~/libs/rbac/module/tree_help.js"></script>
<script type="text/javascript">
    $(function () {
        moduleTreeHelp.init({
            urlSearchModules: "@Html.Raw(Url.Action("GetModulesSimpleInfoByPage", "Module", new { pageNumber = 1, pageSize = 1000 }))",
            singleSelect:true,
        });
    });
</script>